In [1]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Requirement already satisfied: pandas in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\yarem\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\yarem\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.2)
Requirement already satisfied: matplotlib in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (2.5.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\yarem\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\yarem\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\yarem\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\yarem\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\yarem\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\yarem\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: openpyxl in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\yarem\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)

In [2]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Citas_Digital.xlsx')
df

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaT,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaT,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaT,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaT,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaT,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#Filtro por filas
#filtro1= df.iloc[3:10,: ]           #Filas consecutivas
#filtro1=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas
#filtro1= df.iloc[ [0] + list(range(10, 14)) + [50] , [0, 1] ]  #Filas combinadas
filtro1= df.iloc[0:673,: ]
filtro1.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       657 non-null    object
 1   Fecha                                     72 non-null     datetime64[us]
 2   Nombre Cliente                            652 non-null    object
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           638 non-null    object
 5   Potencial de compra                       599 non-null    object
 6   PDM                                       672 non-null    float64
 7   SDC                                       671 non-null    float64
 8   Venta                                     668 non-null    float64
 9   Asesor Asignado                           641 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 84.3+ KB

In [5]:
#Filtro por columnas
#filtro2=df.iloc[ : , 0:3]       #Columnas consecutivas
#filtro2=df.iloc[ : , [1,4,6]]  #Columnas no consecutivas
#filtro2= df.iloc[ :, list(range(1, 6)) + 9]  #Filas combinadas
filtro2 = df.iloc[ : , list(range(0, 3))+ list(range(4, 15))] #En los rangos se debe colocar +1 del limite superior
filtro2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 14 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   BDC                                       673 non-null      object
 1   Fecha                                     88 non-null       datetime64[us]
 2   Nombre Cliente                            668 non-null      object
 3   Estatus de Lead                           654 non-null      object
 4   Potencial de compra                       614 non-null      object
 5   PDM                                       1048574 non-null  float64
 6   SDC                                       1048573 non-null  float64
 7   Venta                                     1048570 non-null  float64
 8   Asesor Asignado                           656 non-null      str
 9   ¿Por que no ha visitado la agencia?       493 non-null      str
 10  ¿Por que no hay solicitud de credito?     379 non-null      str
 11  ¿Por que no hubo prueba de manejo ?       355 non-null      str
 12  ¿Por que no hubo proceso wow?             364 non-null      str
 13  ¿Por que se asigno antes de vistar piso?  353 non-null      str
dtypes: datetime64[us](1), float64(3), object(4), str(6)
memory usage: 112.0+ MB

In [6]:
#Convertir archivo filtrado a CSV
filtro2.to_csv("Citas_Digital_Filtrado.csv", index=False)

In [7]:
#Leemos el archivo filtrado para convertirlo en Dataframe
df_filtrado= pd.read_csv("Citas_Digital_Filtrado.csv")
df_filtrado.info()

C:\Users\yarem\AppData\Local\Temp\ipykernel_3900\3915024761.py:2: DtypeWarning: Columns (0: BDC , 1: Fecha, 2: Nombre Cliente , 3: Estatus de Lead, 4: Potencial de compra, 5: Asesor Asignado, 6: ¿Por que no ha visitado la agencia?, 7: ¿Por que no hay solicitud de credito?, 8: ¿Por que no hubo prueba de manejo ?, 9: ¿Por que no hubo proceso wow?, 10: ¿Por que se asigno antes de vistar piso?) have mixed types. Specify dtype option on import or set low_memory=False.
  df_filtrado= pd.read_csv("Citas_Digital_Filtrado.csv")

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 14 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   BDC                                       673 non-null      str
 1   Fecha                                     88 non-null       str
 2   Nombre Cliente                            668 non-null      str
 3   Estatus de Lead                           654 non-null      str
 4   Potencial de compra                       614 non-null      str
 5   PDM                                       1048574 non-null  float64
 6   SDC                                       1048573 non-null  float64
 7   Venta                                     1048570 non-null  float64
 8   Asesor Asignado                           656 non-null      str
 9   ¿Por que no ha visitado la agencia?       493 non-null      str
 10  ¿Por que no hay solicitud de credito?     379 non-null      str
 11  ¿Por que no hubo prueba de manejo ?       355 non-null      str
 12  ¿Por que no hubo proceso wow?             364 non-null      str
 13  ¿Por que se asigno antes de vistar piso?  353 non-null      str
dtypes: float64(3), str(11)
memory usage: 112.0 MB

In [19]:
#Filtro por comparacion
filtro3=df_filtrado[df_filtrado["Potencial de compra"] < 0.5]
filtro3

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
1,Saul,NaN,Roberto,Finalizado,0.40,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
6,Saul,NaN,Juan Carlos,Finalizado,0.20,0.0,0.0,0.0,Ricardo,"Se programo la visita dos dias, pero nunca asi...",Comento que firmaba en cuando visitara la agen...,No visito la agencia,El el proceso de BDC siempre hubo la atencion ...,Se asgino antes por recomendacion de Gerencia ...
20,Antonio,NaN,Mercy,Finalizado,0.20,1.0,0.0,0.0,pedro,ya visito la agencia,"No quizo, solo queria boletos del cine",Si realizo prueba de manejo,Recibio la atencion,Se asigna en la visita
26,Saul,NaN,Roberto Luis Pacheco,Activo,0.40,0.0,0.0,0.0,Pedro,"Ya visito la agencia, llego desde Oaxaca",Comenta que la unidad,Le gusto la unidad pero comenta que no es para...,Recibio la atencion,Se asigno hasta que visitara Piso
32,Saul,NaN,13,11,0.00,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Antonio,NaN,Jaime Juarez,Acitvo,0.05,1.0,1.0,0.0,Mauricio,Ya visito la agencia,Ya esta pre aprobado,Ya realizo prueba de manejo,Recibio la atencion,Se asigna en la visita
502,Ignacio,NaN,Salvador Jasso,Activo,0.30,1.0,0.0,0.0,Mauricio,Ya visito la agencia,depende del padres,NaN,NaN,NaN
503,Ignacio,NaN,Luis Pelcastre,Activo,0.30,0.0,0.0,0.0,Mauricio,Ya visito la agencia,NaN,NaN,NaN,NaN
531,NaN,NaN,Alejandro Sanchez,Activo,0.30,0.0,0.0,0.0,Julio Cesar,NaN,NaN,NaN,NaN,NaN
532,NaN,NaN,Cesar Palafox,Activo,0.30,0.0,0.0,0.0,Vanny,NaN,NaN,NaN,NaN,NaN

In [18]:
#Conversión de tipo de dato de columna de tipo String a Float
df_filtrado['Potencial de compra']= df_filtrado['Potencial de compra'].astype(float)

In [10]:
#Reemplazo de datos de una columna 
df_filtrado['Potencial de compra']=df_filtrado['Potencial de compra'].str.replace("Ventas ","0", regex=False)

In [11]:
df_filtrado['Potencial de compra']=df_filtrado['Potencial de compra'].str.replace("%","", regex=False)

In [14]:
df_filtrado['Potencial de compra']=df_filtrado['Potencial de compra'].str.replace("'","", regex=False)

In [17]:
df_filtrado['Potencial de compra']=df_filtrado['Potencial de compra'].str.replace("&","", regex=False)

In [20]:
#Convertir archivo filtrado a CSV
filtro3.to_csv("Citas_Digital_General.csv", index=False)

In [21]:
df_general = pd.read_csv("Citas_Digital_General.csv")

In [26]:
df_general["Fecha"] = pd.to_datetime(df_general["Fecha"], errors="coerce")

In [23]:
meses = pd.date_range(start="2025-04-01", end="2026-07-01", freq="MS")

In [27]:
for mes in meses:
    
    # Fecha inicial del mes
    fecha_inicio = mes
    
    # Fecha inicial del siguiente mes
    fecha_fin = mes + pd.DateOffset(months=1)
    
    # Filtramos las filas correspondientes al mes
    filtro_mes = df_general[
        (df_general["Fecha"] >= fecha_inicio) &
        (df_general["Fecha"] < fecha_fin)
    ]

     # Nombre del mes en español
    meses_espanol = {
        1: "Enero",
        2: "Febrero",
        3: "Marzo",
        4: "Abril",
        5: "Mayo",
        6: "Junio",
        7: "Julio",
        8: "Agosto",
        9: "Septiembre",
        10: "Octubre",
        11: "Noviembre",
        12: "Diciembre"
    }
    
    nombre_mes = meses_espanol[mes.month]

In [28]:
  nombre_archivo = f"{nombre_mes}_{mes.year}.csv"

In [29]:
filtro_mes.to_csv(nombre_archivo, index=False)

In [30]:
print(f"{nombre_archivo} creado con {len(filtro_mes)} registros.")

Julio_2026.csv creado con 0 registros.